/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GithubPane: typeof import('./src/components/GithubPane.vue')['default']
    IconFork: typeof import('./src/components/icons/iconFork.vue')['default']
    IconGithub: typeof import('./src/components/icons/iconGithub.vue')['default']
    IconStar: typeof import('./src/components/icons/iconStar.vue')['default']
    IconTranslate: typeof import('./src/components/icons/iconTranslate.vue')['default']
    ImplementDetail: typeof import('./src/components/ImplementDetail.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    RiskDetail: typeof import('./src/components/RiskDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreatenDetail: typeof import('./src/components/ThreatenDetail.vue')['default']
  }
}
